// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvWU7kGD7uuDdBu3o2nOg_bwm-P7vegHQ',
    appId: '1:385493680601:web:91ecaf23af7701e4da59c8',
    messagingSenderId: '385493680601',
    projectId: 'rps-first-project',
    authDomain: 'rps-first-project.firebaseapp.com',
    storageBucket: 'rps-first-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJMNaLczvAuTMLsiwMiIL0wGkCysb7wc',
    appId: '1:385493680601:android:0c1cb9607bbdc50eda59c8',
    messagingSenderId: '385493680601',
    projectId: 'rps-first-project',
    storageBucket: 'rps-first-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiOvcJJWNnXEf4Tjpj0-wM5g0mrHdHrMk',
    appId: '1:385493680601:ios:bad4a959d27cbc10da59c8',
    messagingSenderId: '385493680601',
    projectId: 'rps-first-project',
    storageBucket: 'rps-first-project.appspot.com',
    iosBundleId: 'com.example.pratice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiOvcJJWNnXEf4Tjpj0-wM5g0mrHdHrMk',
    appId: '1:385493680601:ios:bad4a959d27cbc10da59c8',
    messagingSenderId: '385493680601',
    projectId: 'rps-first-project',
    storageBucket: 'rps-first-project.appspot.com',
    iosBundleId: 'com.example.pratice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvWU7kGD7uuDdBu3o2nOg_bwm-P7vegHQ',
    appId: '1:385493680601:web:11c2e9d6506c7da6da59c8',
    messagingSenderId: '385493680601',
    projectId: 'rps-first-project',
    authDomain: 'rps-first-project.firebaseapp.com',
    storageBucket: 'rps-first-project.appspot.com',
  );
}
